# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

azure_account_name: ""
azure_account_key: ""
azure_container_name: dockerregistry
registry_listener: ":5000"
container_port: 5000
service_port: 5000
service_nodeport: 35000
remote_url: https://registry-1.docker.io
registry-htpasswd: dGVzdDokMnkkMDUkRUZiaWphaHovMHl4UC5xMFk1VW52TzljU2hHMThCRzM3QzBHNFhoRmFtTXdTUXdQLjBqQi4KCg==