# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

azure_account_name: ""
azure_account_key: ""
azure_container_name: dockerregistry
registry_listener: ":5000"
container_port: 5000
service_port: 5000
host_name: registry.openpai.org
uri: http://registry.openpai.org:5000/
remote_url: https://registry-1.docker.io
registry-htpasswd: dGVzdDokMnkkMDUkRUZiaWphaHovMHl4UC5xMFk1VW52TzljU2hHMThCRzM3QzBHNFhoRmFtTXdTUXdQLjBqQi4KCg==