---
- name: "Detect NVIDIA gpu card"
  raw: lspci | grep NVIDIA
  register: nvidia_detect_result
  failed_when: false
  changed_when: false
  check_mode: false
  environment: {}

- name: "If NVIDIA card exits, import NVIDIA drivers installation task"
  include_tasks: ubuntu-nvidia.yml
  when: nvidia_detect_result.rc == 0

- name: "If NVIDIA card exits, enable NVIDIA persistent mode"
  fail:
    msg: "NVIDIA GPU drivers is detected in your machines, please uninstall it first."
  changed_when: false
  check_mode: false
  environment: {}
  when:
    - nvidia_smi_check.rc == 0