---
- name: "Check NVIDIA GPU drivers"
  raw: "nvidia-smi"
  register: nvidia_smi_check
  failed_when: false
  changed_when: false
  check_mode: false
  environment: {}

- name: "Quit playbooks, if NVIDIA GPU drivers exit."
  fail:
    msg: "NVIDIA GPU drivers is detected in your machines, please uninstall it first."
  changed_when: false
  check_mode: false
  environment: {}
  when:
    - nvidia_smi_check.rc == 0

- name: Add the drivers repository to Ubuntu
  apt_repository:
    repo: ppa:graphics-drivers/ppa
    state: present

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Install nvidia drivers on ubuntu 16.04, we will install {{ nvidia_version }} version
  apt:
    name: nvidia-{{ nvidia_version }}
    state: present
  when: ansible_distribution_version == '16.04'

- name: Install nvidia drivers on ubuntu 18.04, we will install {{ nvidia_version }} version
  apt:
    name: nvidia-driver-{{ nvidia_version }}
    state: present
  when: ansible_distribution_version == '18.04'

- name: reboot vm
  reboot:

- name: create persistenced override dir
  file:
    path: /etc/systemd/system/nvidia-persistenced.service.d/
    state: directory
    recurse: yes

- name: configure persistenced service to turn on persistence mode
  copy:
    src: nvidia-persistenced-override.conf
    dest: /etc/systemd/system/nvidia-persistenced.service.d/override.conf

- name: enable persistenced
  systemd:
    name: nvidia-persistenced
    enabled: yes

- name: perform nvidia smi
  shell: nvidia-smi
  args:
    executable: /bin/bash
