---
- hosts: all
  tasks:
    - name: fix-apt-key
      shell: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6ED91CA3AC1160CD
      args:
        executable: /bin/bash

    - name: remove cephlist
      shell: rm -rf  /etc/apt/sources.list.d/ceph.list
      args:
        executable: /bin/bash

    - name: apt-get update
      shell: apt-get update
      args:
        executable: /bin/bash


