---
- hosts: all
  tasks:
    - name: create docker etc
      file:
        path: /etc/docker-openpai
        state: directory
        recurse: yes

    - name: copy file
      copy:
        src: daemon-openpai.json
        dest: /etc/docker-openpai/daemon-openpai.json

