- hosts: all
  become: true
  become_user: root
  gather_facts: true
  roles:
    - { role: '../roles/docker-cache/install', enable_docker_cache: true }
  tasks:
    - name: Restart service docker config from /etc/docker/daemon.json after update
      ansible.builtin.systemd:
        name: docker
        state: reloaded
