- hosts: all
  become: true
  become_user: root
  gather_facts: true
  roles:
    - role: '../roles/docker-cache/install'
      vars:
        docker_cache_host: "{{ hostvars[groups['kube-master'][0]]['ip'] }}:30500"