---
- hosts: all
  gather_facts: false
  tasks:
    - name: "SSH test from dev-box to all machine of infra and worker"
      ping:

- hosts: localhost
  become: true
  become_user: root
  roles:
    - { role: requirement/devbox }

#- hosts: infra
#  gather_facts: false
#  roles:
#    - { role: requirement/infra }

#- hosts: worker
#  gather_facts: false
#  roles:
#    - { role: requirement/worker }
