# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

service_type: "common"

user: user
passwd: passwd
db: marketplace
port: 9291
max-connection: 1000
data-path: /mnt/marketplace
