---
- name: "Check NVIDIA GPU drivers"
  raw: "nvidia-smi"
  register: nvidia_smi_check
  failed_when: false
  changed_when: false
  check_mode: false
  environment: {}

- name: "Nvidia-smi is detected, include nvidia docker runtime task"
  include_tasks: nvidia-runtime.yml
  when:
    - nvidia_smi_check.rc == 0 and not enable_docker_cache

- name: "Nvidia-smi is detected, docker-cache enabled, include nvidia docker runtime task"
  include_tasks: nvidia-runtime-with-docker-cache.yml
  when:
    - nvidia_smi_check.rc == 0 and enable_docker_cache

- name: "Nvidia-smi is not detected, include default docker runtime task"
  include_tasks: default-runtime.yml
  when:
    - nvidia_smi_check.rc != 0 and not enable_docker_cache

- name: "Nvidia-smi is not detected, docker-cache enabled, include default docker runtime task"
  include_tasks: default-runtime-with-docker-cache.yml
  when:
    - nvidia_smi_check.rc != 0 and enable_docker_cache
