FROM aiplatform/pai.run.cntk

# install git
RUN apt-get -y update && apt-get -y install git

# install Keras using pip
RUN pip install keras cntk-gpu

# clone Keras examples
RUN git clone git clone https://github.com/keras-team/keras.git 

ENV KERAS_BACKEND cntk

WORKDIR /keras/examples