---
- name: "Check Enflame DTU card info with lspci"
  raw: "lspci -d 1e36: | grep ."
  register: lspci_grep
  failed_when: false
  changed_when: false
  check_mode: false
  environment: {}

- name: "Check Enflame DTU exits or not"
  set_fact:
    unmet_requirements: "{{ unmet_requirements + ['Enflame DTU card is not detected'] }}"
  changed_when: false
  check_mode: false
  environment: {}
  when:
    - lspci_grep.rc != 0

- name: "Check Enflame DTU drivers with efsmi"
  raw: "efsmi"
  register: efsmi
  failed_when: false
  changed_when: false
  check_mode: false
  environment: {}

- name: "Check Enflame DTU drivers is installed or not "
  set_fact:
    unmet_requirements: "{{ unmet_requirements + ['Enflame DTU drivers is not detected'] }}"
  changed_when: false
  check_mode: false
  environment: {}
  when:
    - efsmi.rc != 0

- name: "Check Enflame DTU card number with efsmi"
  raw: "efsmi -L | grep -E '^DTU ' | wc -l"
  register: enflame_dtu_count
  failed_when: false
  changed_when: false
  check_mode: false
  environment: {}
  when:
    # if efsmi doesn't work, we can skip this step
    - efsmi.rc == 0 

- name: "Check Enflame DTU card number is matched or not"
  set_fact:
    unmet_requirements: "{{ unmet_requirements + [\"Enflame DTU card number is not matched: {{ computing_device_count }} specified but only {{ enflame_dtu_count.stdout_lines[0] }} found\"] }}"
  changed_when: false
  check_mode: false
  environment: {}
  when:
    # if efsmi doesn't work, we can skip this step
    - efsmi.rc == 0
    - "enflame_dtu_count.stdout_lines[0]|int != computing_device_count"
    - enflame_dtu_count.rc == 0

- name: "Check Enflame container runtime with command"
  raw: "command -v enflame-container-runtime"
  register: enflame_container_runtime
  failed_when: false
  changed_when: false
  check_mode: false
  environment: {}

- name: "Check Enflame container runtime is installed or not"
  set_fact:
    unmet_requirements: "{{ unmet_requirements + ['Enflame container runtime is not detected'] }}"
  changed_when: false
  check_mode: false
  environment: {}
  when:
    - enflame_container_runtime.rc != 0

- name: "Get default docker runtime"
  raw: "{% raw %} docker info -f '{{json .DefaultRuntime}}'{% endraw %}"
  register: default_runtime
  failed_when: false
  changed_when: false
  check_mode: false
  environment: {}

- name: "Init array"
  set_fact:
    default_runtime_processed: []

- name: "Remove unnecessary char in the end of the output"
  set_fact:
    default_runtime_processed: "{{ default_runtime_processed + [ item | replace('\"','') ] }}"
  loop: "{{ default_runtime.stdout_lines }}"

- name: "Get Default Runtime"
  set_fact:
    default_runtime_find: "{{ item }}"
  when: item == 'enflame'
  loop: "{{default_runtime_processed}}"

- name: "Check the default runtime is set correctly"
  set_fact:
    unmet_requirements: "{{ unmet_requirements + ['The default runtime is not set correctly'] }}"
  changed_when: false
  check_mode: false
  environment: {}
  when:
    - default_runtime_find is not defined
