FROM aiplatform/pai.run.tensorflow

# install git
RUN apt-get -y update && apt-get -y install git

# install Keras using pip
RUN pip install keras

WORKDIR /root

# clone Keras examples
RUN git clone https://github.com/keras-team/keras.git 

ENV KERAS_BACKEND tensorflow

WORKDIR /root/keras/examples