---
- name: "Worker-Task-1-[1/2] Check whether the vm can access to docker.io"
  raw: nslookup index.docker.io
  register: worker_nslookup_docker_io
  failed_when: false
  changed_when: false
  check_mode: false
  environment: {}

- name: "Worker-Task-1-[2/2] Check whether the vm can access to docker.io"
  fail:
    msg: "Unable to access docker.io"
  changed_when: false
  check_mode: false
  environment: {}
  when:
    - worker_nslookup_docker_io.rc != 0

- name: "Worker-Task-2-[1/3] Check whether the NTP is installed and enabled."
  raw: pgrep ntpd
  register: worker_pgrep_ntpd
  failed_when: false
  changed_when: false
  check_mode: false
  environment: {}

- name: "Worker-Task-2-[2/3] Check whether the NTP is installed and enabled."
  raw: ntpq -p
  register: worker_ntpq
  faled_when: false
  changed_when: false
  check_mode: false
  environment: {}

- name: "Worker-Task-2-[3/3] Check whether the NTP is installed and enabled."
  fail:
    msg: "NTP is not enabled on your infra machines."
  changed_when: false
  check_mode: false
  environment: {}
  when:
    - worker_ntpq.rc != 0 or worker_nslookup_docker_io.rc != 0

