version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/src/rest-server"
    update_schedule: "live"
    target_branch: "master"
    default_reviewers:
    - abuccts
    - sunqinzheng
    default_labels:
    - "dependencies"
    - "security"
    - "javascript"
    allowed_updates:
    - match:
        update_type: "security"

  - package_manager: "javascript"
    directory: "/src/webportal"
    update_schedule: "live"
    target_branch: "master"
    default_reviewers:
    - abuccts
    - sunqinzheng
    default_labels:
    - "dependencies"
    - "security"
    - "javascript"
    allowed_updates:
    - match:
        update_type: "security"

  - package_manager: "javascript"
    directory: "/contrib"
    update_schedule: "live"
    target_branch: "master"
    default_reviewers:
    - abuccts
    - sunqinzheng
    default_labels:
    - "dependencies"
    - "security"
    - "javascript"
    allowed_updates:
    - match:
        update_type: "security"
