protocol_version: v2
name : mnist_pytorch
type : job
version : 1.0.0
contributor : Qi Chen
description : image classification, mnist dataset, pytorch
retryCount: 0
parameters :
  epochs : 10
  batchsize: 32
  lr : 0.01

tasks :
  - role: worker
    script : pytorch_examples
    dockerimage : pytorch_example
    resource: 
      instances : 1
      resourcePerInstance: {cpu: 4, memoryMB: 8192, gpu: 1}
    parameters:
      epochs: $$epochs$$
      batchsize: $$batchsize$$
      lr: $$lr$$
    command:
      - python pytorch_examples/mnist/main.py --epochs $$epochs$$ --lr $$lr$$ --batch-size $$batchsize$$

prerequisites : 
  - protocol_version : v2
    name : pytorch_examples
    type : script
    version : 1.0.0
    contributor : Qi Chen
    description: pytorch examples
    uri : https://github.com/pytorch/examples
    usage:
      parameters:
        epochs: 10
        batchsize: 32
        lr: 0.01
      roles:
        - name : worker
          command : 
            - python pytorch_examples/mnist/main.py --epochs $$epochs$$ --lr $$lr$$ --batch-size $$batchsize$$
  - protocol_version : v2
    name : pytorch_example
    type : dockerimage
    version : 1.0.0
    contributor : Qi Chen
    description: python3.5, pytorch
    uri : openpai/pai.example.pytorch
