# If you set OIDC as the value false, the basic authentication will be applied to your cluster.
OIDC: false

#######################################################################################################################
##########################################     OIDC Configuration    ##################################################
#######################################################################################################################

# If OIDC is set as the value true, you will have to configure the following properties.
#OIDC-type: AAD
#
#AAD:
#  # If you wanna configure AAD-OIDC for OpenPAI, the following configuration is mandatory.
#  tenantID: ${tenat_id}
#
#  # Required, the client ID of your app in AAD
#  clientID: ${your_client_id}
#
#  # Required if `responseType` is 'code', 'id_token code' or 'code id_token'.
#  # If app key contains '\', replace it with '\\'.
#  clientSecret: '${your_client_secret}'
#
#  # Optional. The lifetime of nonce in session or cookie, the default value is 3600 (seconds).
#  nonceLifetime: null
#
#  # Optional. The max amount of nonce saved in session or cookie, the default value is 10.
#  nonceMaxAmount: 5
#
#  # Optional. The clock skew allowed in token validation, the default value is 300 seconds.
#  clockSkew: null


#######################################################################################################################
####################################   Group ManagerConfiguration    ##################################################
#######################################################################################################################

group-manager:
  # basic: If you set group-data-source as the value basic, admin should manually modify user's grouplist.
  # winbind: If you set group-data-source as the value winbind, the user's grouplist will get from winbind server based on your configuration.
  group-data-source: basic

  # If you set winbind as your data source, you should configure this configuraiton.
  # winbind-server-address: xxxxxxx

  # Admin group name and its user list
  admin-group:
    groupname: admingroup
    description: "admin's group"
    externalName: ""
    # In admin group, you can manually add user to it. If you don't want to add a new admin user to OpenPAI,
    # please remove this field.
    userlist:
      - openpai

  # Group for default vc.
  # For yarn default queue hack.
  default-group:
    groupname: default
    description: "group for default vc"
    externalName: ""

  # If the following groups are not in the data store, it will be created by default.
  grouplist:
    - groupname: for-example
      # internal name
      description: for-example
      # description of the group
      externalName: ""
      # external name, it should be set if your group-data-source is winbind. And the name will be used to query and match the group from
      # the result of winbind. If the group-data-source is basic, this field is useless.