'use strict';

// webHdfsUri is currently not used
const clustersConfig = {
    'Clusters': [
        {
            'Name': 'BN1-0',
            'RestServerUri': 'https://apigw-ivip.yarn3-dev-bn1.bn1.ap.gbl:4431',
            'hdfsUri': 'hdfs://namenode0-ivip.yarn3-dev-bn1.bn1.ap.gbl',
            'webHdfsUri': 'http://namenode0-ivip.yarn3-dev-bn1.bn1.ap.gbl',
            'HttpFSUri': 'https://apigw-ivip.yarn3-dev-bn1.bn1.ap.gbl:4436',
            'resourceManagerUri': 'https://apigw-ivip.yarn3-dev-bn1.bn1.ap.gbl:4435',
            'subCluster': 'BASIC-DEV-BN1-0',
            'proxyUri': 'https://webportal-ivip.yarn-prod-ch1.ch1.ap.gbl/cache',
        },
        {
            'Name': 'CH1-0',
            'RestServerUri': 'https://apigw-ivip.yarn-prod-ch1.ch1.ap.gbl:4431',
            'hdfsUri': 'hdfs://namenode0-ivip.yarn-prod-ch1.ch1.ap.gbl',
            'webHdfsUri': 'http://namenode0-ivip.yarn-prod-ch1.ch1.ap.gbl',
            'HttpFSUri': 'https://apigw-ivip.yarn-prod-ch1.ch1.ap.gbl:4436',
            'HttpFSAPIPath': '/webhdfs/v1/CH1',
            'resourceManagerUri': 'https://apigw-ivip.yarn-prod-ch1.ch1.ap.gbl:4435',
            'subCluster': 'BASIC-PROD-CH1-0',
            'proxyUri': 'https://magnetar/cache',
        },
        {
            'Name': 'CH1-1',
            'RestServerUri': 'https://apigw-ivip.yarn-prod-ch1.ch1.ap.gbl:4431',
            'hdfsUri': 'hdfs://namenode1-ivip.yarn-prod-ch1.ch1.ap.gbl',
            'webHdfsUri': 'http://namenode1-ivip.yarn-prod-ch1.ch1.ap.gbl',
            'HttpFSUri': 'https://apigw-ivip.yarn-prod-ch1.ch1.ap.gbl:4436',
            'HttpFSAPIPath': '/webhdfs/v1/CH1-1',
            'resourceManagerUri': 'https://apigw-ivip.yarn-prod-ch1.ch1.ap.gbl:4435',
            'subCluster': 'BASIC-PROD-CH1-1',
            'proxyUri': 'https://magnetar/cache',
        },
        {
            'Name': 'BN1-1',
            'RestServerUri': 'https://apigw-ivip.yarn3-dev-bn1.bn1.ap.gbl:4431',
            'hdfsUri': 'hdfs://namenode1-ivip.yarn3-dev-bn1.bn1.ap.gbl',
            'webHdfsUri': 'http://namenode1-ivip.yarn3-dev-bn1.bn1.ap.gbl',
            'HttpFSUri': 'https://apigw-ivip.yarn3-dev-bn1.bn1.ap.gbl:4436',
            'resourceManagerUri': 'https://apigw-ivip.yarn3-dev-bn1.bn1.ap.gbl:4435',
            'subCluster': 'BASIC-DEV-BN1-1',
            'proxyUri': 'https://webportal-ivip.yarn-prod-ch1.ch1.ap.gbl/cache',
        },
        {
            'Name': 'CO4-0',
            'RestServerUri': 'https://apigw-ivip.yarn-prod-co4.co4.ap.gbl:4431',
            'hdfsUri': 'hdfs://namenode0-ivip.yarn-prod-co4.co4.ap.gbl',
            'webHdfsUri': 'http://namenode0-ivip.yarn-prod-co4.co4.ap.gbl',
            'HttpFSUri': 'https://apigw-ivip.yarn-prod-co4.co4.ap.gbl:4436',
            'HttpFSAPIPath': '/webhdfs/v1/CO4',
            'resourceManagerUri': 'https://apigw-ivip.yarn-prod-co4.co4.ap.gbl:4435',
            'subCluster': 'BASIC-PROD-CO4-0',
            'proxyUri': 'https://magnetar/cache',
        },
        {
            'Name': 'CO4-1',
            'RestServerUri': 'https://apigw-ivip.yarn-prod-co4.co4.ap.gbl:4431',
            'hdfsUri': 'hdfs://namenode1-ivip.yarn-prod-co4.co4.ap.gbl',
            'webHdfsUri': 'http://namenode1-ivip.yarn-prod-co4.co4.ap.gbl',
            'HttpFSUri': 'https://apigw-ivip.yarn-prod-co4.co4.ap.gbl:4436',
            'HttpFSAPIPath': '/webhdfs/v1/CO4-1',
            'resourceManagerUri': 'https://apigw-ivip.yarn-prod-co4.co4.ap.gbl:4435',
            'subCluster': 'BASIC-PROD-CO4-1',
            'proxyUri': 'https://magnetar/cache',
        },
        {
            'Name': 'CO4-2',
            'RestServerUri': 'https://apigw-ivip.yarn-prod-co4.co4.ap.gbl:4431',
            'hdfsUri': 'hdfs://namenode2-ivip.yarn-prod-co4.co4.ap.gbl',
            'webHdfsUri': 'http://namenode2-ivip.yarn-prod-co4.co4.ap.gbl',
            'HttpFSUri': 'https://apigw-ivip.yarn-prod-co4.co4.ap.gbl:4436',
            'HttpFSAPIPath': '/webhdfs/v1/CO4-2',
            'resourceManagerUri': 'https://apigw-ivip.yarn-prod-co4.co4.ap.gbl:4435',
            'subCluster': 'BASIC-PROD-CO4-2',
            'proxyUri': 'https://magnetar/cache',
        },
        {
            'Name': 'CO4-3',
            'RestServerUri': 'https://apigw-ivip.yarn-prod-co4.co4.ap.gbl:4431',
            'hdfsUri': 'hdfs://namenode3-ivip.yarn-prod-co4.co4.ap.gbl',
            'webHdfsUri': 'http://namenode3-ivip.yarn-prod-co4.co4.ap.gbl',
            'HttpFSUri': 'https://apigw-ivip.yarn-prod-co4.co4.ap.gbl:4436',
            'HttpFSAPIPath': '/webhdfs/v1/CO4-3',
            'resourceManagerUri': 'https://apigw-ivip.yarn-prod-co4.co4.ap.gbl:4435',
            'subCluster': 'BASIC-PROD-CO4-3',
            'proxyUri': 'https://magnetar/cache',
        },
        {
            'Name': 'CO4-4',
            'RestServerUri': 'https://apigw-ivip.yarn-prod-co4.co4.ap.gbl:4431',
            'hdfsUri': 'hdfs://namenode4-ivip.yarn-prod-co4.co4.ap.gbl',
            'webHdfsUri': 'http://namenode4-ivip.yarn-prod-co4.co4.ap.gbl',
            'HttpFSUri': 'https://apigw-ivip.yarn-prod-co4.co4.ap.gbl:4436',
            'HttpFSAPIPath': '/webhdfs/v1/CO4-4',
            'resourceManagerUri': 'https://apigw-ivip.yarn-prod-co4.co4.ap.gbl:4435',
            'subCluster': 'BASIC-PROD-CO4-4',
            'proxyUri': 'https://magnetar/cache',
        },
        {
            'Name': 'CO4-5',
            'RestServerUri': 'https://apigw-ivip.yarn-prod-co4.co4.ap.gbl:4431',
            'hdfsUri': 'hdfs://namenode5-ivip.yarn-prod-co4.co4.ap.gbl',
            'webHdfsUri': 'http://namenode5-ivip.yarn-prod-co4.co4.ap.gbl',
            'HttpFSUri': 'https://apigw-ivip.yarn-prod-co4.co4.ap.gbl:4436',
            'HttpFSAPIPath': '/webhdfs/v1/CO4-5',
            'resourceManagerUri': 'https://apigw-ivip.yarn-prod-co4.co4.ap.gbl:4435',
            'subCluster': 'BASIC-PROD-CO4-5',
            'proxyUri': 'https://magnetar/cache',
        },
        {
            'Name': 'BN2-0',
            'RestServerUri': 'https://apigw-ivip.yarn-prod-bn2.bn2.ap.gbl:4431',
            'hdfsUri': 'hdfs://namenode0-ivip.yarn-prod-bn2.bn2.ap.gbl',
            'webHdfsUri': 'http://namenode0-ivip.yarn-prod-bn2.bn2.ap.gbl',
            'HttpFSUri': 'https://apigw-ivip.yarn-prod-bn2.bn2.ap.gbl:4436',
            'HttpFSAPIPath': '/webhdfs/v1/BN2',
            'resourceManagerUri': 'https://apigw-ivip.yarn-prod-bn2.bn2.ap.gbl:4435',
            'subCluster': 'BASIC-PROD-BN2-0',
            'proxyUri': 'https://magnetar/cache',
        },
        {
            'Name': 'BN2-1',
            'RestServerUri': 'https://apigw-ivip.yarn-prod-bn2.bn2.ap.gbl:4431',
            'hdfsUri': 'hdfs://namenode1-ivip.yarn-prod-bn2.bn2.ap.gbl',
            'webHdfsUri': 'hdfs://namenode1-ivip.yarn-prod-bn2.bn2.ap.gbl',
            'HttpFSUri': 'https://apigw-ivip.yarn-prod-bn2.bn2.ap.gbl:4436',
            'HttpFSAPIPath': '/webhdfs/v1/BN2-1',
            'resourceManagerUri': 'https://apigw-ivip.yarn-prod-bn2.bn2.ap.gbl:4435',
            'subCluster': 'BASIC-PROD-BN2-1',
            'proxyUri': 'https://magnetar/cache',
        },
        {
            'Name': 'BN2-2',
            'RestServerUri': 'https://apigw-ivip.yarn-prod-bn2.bn2.ap.gbl:4431',
            'hdfsUri': 'hdfs://namenode2-ivip.yarn-prod-bn2.bn2.ap.gbl',
            'webHdfsUri': 'http://namenode2-ivip.yarn-prod-bn2.bn2.ap.gbl',
            'HttpFSUri': 'https://apigw-ivip.yarn-prod-bn2.bn2.ap.gbl:4436',
            'HttpFSAPIPath': '/webhdfs/v1/BN2-2',
            'resourceManagerUri': 'https://apigw-ivip.yarn-prod-bn2.bn2.ap.gbl:4435',
            'subCluster': 'BASIC-PROD-BN2-2',
            'proxyUri': 'https://magnetar/cache',
        },
        {
            'Name': 'BN2-3',
            'RestServerUri': 'https://apigw-ivip.yarn-prod-bn2.bn2.ap.gbl:4431',
            'hdfsUri': 'hdfs://namenode3-ivip.yarn-prod-bn2.bn2.ap.gbl',
            'webHdfsUri': 'http://namenode3-ivip.yarn-prod-bn2.bn2.ap.gbl',
            'HttpFSUri': 'https://apigw-ivip.yarn-prod-bn2.bn2.ap.gbl:4436',
            'HttpFSAPIPath': '/webhdfs/v1/BN2-3',
            'resourceManagerUri': 'https://apigw-ivip.yarn-prod-bn2.bn2.ap.gbl:4435',
            'subCluster': 'BASIC-PROD-BN2-3',
            'proxyUri': 'https://magnetar/cache',
        },
        {
            'Name': 'BN2-4',
            'RestServerUri': 'https://apigw-ivip.yarn-prod-bn2.bn2.ap.gbl:4431',
            'hdfsUri': 'hdfs://namenode4-ivip.yarn-prod-bn2.bn2.ap.gbl',
            'webHdfsUri': 'http://namenode4-ivip.yarn-prod-bn2.bn2.ap.gbl',
            'HttpFSUri': 'https://apigw-ivip.yarn-prod-bn2.bn2.ap.gbl:4436',
            'HttpFSAPIPath': '/webhdfs/v1/BN2-4',
            'resourceManagerUri': 'https://apigw-ivip.yarn-prod-bn2.bn2.ap.gbl:4435',
            'subCluster': 'BASIC-PROD-BN2-4',
            'proxyUri': 'https://magnetar/cache',
        },
        {
            'Name': 'BN2-5',
            'RestServerUri': 'https://apigw-ivip.yarn-prod-bn2.bn2.ap.gbl:4431',
            'hdfsUri': 'hdfs://namenode5-ivip.yarn-prod-bn2.bn2.ap.gbl',
            'webHdfsUri': 'http://namenode5-ivip.yarn-prod-bn2.bn2.ap.gbl',
            'HttpFSUri': 'https://apigw-ivip.yarn-prod-bn2.bn2.ap.gbl:4436',
            'HttpFSAPIPath': '/webhdfs/v1/BN2-5',
            'resourceManagerUri': 'https://apigw-ivip.yarn-prod-bn2.bn2.ap.gbl:4435',
            'subCluster': 'BASIC-PROD-BN2-5',
            'proxyUri': 'https://magnetar/cache',
        },
        {
            'Name': 'CH1B-0',
            'RestServerUri': 'https://apigw-ivip.yarn-prod-ch1b.ch1b.ap.gbl:4431',
            'hdfsUri': 'hdfs://namenode0-ivip.yarn-prod-ch1b.ch1b.ap.gbl',
            'webHdfsUri': 'http://namenode0-ivip.yarn-prod-ch1b.ch1b.ap.gbl',
            'HttpFSUri': 'https://apigw-ivip.yarn-prod-ch1b.ch1b.ap.gbl:4436',
            'HttpFSAPIPath': '/webhdfs/v1/CH1B',
            'resourceManagerUri': 'https://apigw-ivip.yarn-prod-ch1b.ch1b.ap.gbl:4435',
            'subCluster': 'BASIC-PROD-CH1B-0',
            'proxyUri': 'https://magnetar/cache',
        },
        {
            'Name': 'CH1B-1',
            'RestServerUri': 'https://apigw-ivip.yarn-prod-ch1b.ch1b.ap.gbl:4431',
            'hdfsUri': 'hdfs://namenode1-ivip.yarn-prod-ch1b.ch1b.ap.gbl',
            'webHdfsUri': 'http://namenode1-ivip.yarn-prod-ch1b.ch1b.ap.gbl',
            'HttpFSUri': 'https://apigw-ivip.yarn-prod-ch1b.ch1b.ap.gbl:4436',
            'HttpFSAPIPath': '/webhdfs/v1/CH1B-1',
            'resourceManagerUri': 'https://apigw-ivip.yarn-prod-ch1b.ch1b.ap.gbl:4435',
            'subCluster': 'BASIC-PROD-CH1B-1',
            'proxyUri': 'https://magnetar/cache',
        },
        {
            'Name': 'CH1B-2',
            'RestServerUri': 'https://apigw-ivip.yarn-prod-ch1b.ch1b.ap.gbl:4431',
            'hdfsUri': 'hdfs://namenode2-ivip.yarn-prod-ch1b.ch1b.ap.gbl',
            'webHdfsUri': 'http://namenode2-ivip.yarn-prod-ch1b.ch1b.ap.gbl',
            'HttpFSUri': 'https://apigw-ivip.yarn-prod-ch1b.ch1b.ap.gbl:4436',
            'HttpFSAPIPath': '/webhdfs/v1/CH1B-2',
            'resourceManagerUri': 'https://apigw-ivip.yarn-prod-ch1b.ch1b.ap.gbl:4435',
            'subCluster': 'BASIC-PROD-CH1B-2',
            'proxyUri': 'https://magnetar/cache',
        },
        {
            'Name': 'CH1B-3',
            'RestServerUri': 'https://apigw-ivip.yarn-prod-ch1b.ch1b.ap.gbl:4431',
            'hdfsUri': 'hdfs://namenode3-ivip.yarn-prod-ch1b.ch1b.ap.gbl',
            'webHdfsUri': 'http://namenode3-ivip.yarn-prod-ch1b.ch1b.ap.gbl',
            'HttpFSUri': 'https://apigw-ivip.yarn-prod-ch1b.ch1b.ap.gbl:4436',
            'HttpFSAPIPath': '/webhdfs/v1/CH1B-3',
            'resourceManagerUri': 'https://apigw-ivip.yarn-prod-ch1b.ch1b.ap.gbl:4435',
            'subCluster': 'BASIC-PROD-CH1B-3',
            'proxyUri': 'https://magnetar/cache',
        },
        {
            'Name': 'CH1B-4',
            'RestServerUri': 'https://apigw-ivip.yarn-prod-ch1b.ch1b.ap.gbl:4431',
            'hdfsUri': 'hdfs://namenode4-ivip.yarn-prod-ch1b.ch1b.ap.gbl',
            'webHdfsUri': 'http://namenode4-ivip.yarn-prod-ch1b.ch1b.ap.gbl',
            'HttpFSUri': 'https://apigw-ivip.yarn-prod-ch1b.ch1b.ap.gbl:4436',
            'HttpFSAPIPath': '/webhdfs/v1/CH1B-4',
            'resourceManagerUri': 'https://apigw-ivip.yarn-prod-ch1b.ch1b.ap.gbl:4435',
            'subCluster': 'BASIC-PROD-CH1B-4',
            'proxyUri': 'https://magnetar/cache',
        },
        {
            'Name': 'CH1B-5',
            'RestServerUri': 'https://apigw-ivip.yarn-prod-ch1b.ch1b.ap.gbl:4431',
            'hdfsUri': 'hdfs://namenode5-ivip.yarn-prod-ch1b.ch1b.ap.gbl',
            'webHdfsUri': 'http://namenode5-ivip.yarn-prod-ch1b.ch1b.ap.gbl',
            'HttpFSUri': 'https://apigw-ivip.yarn-prod-ch1b.ch1b.ap.gbl:4436',
            'HttpFSAPIPath': '/webhdfs/v1/CH1B-5',
            'resourceManagerUri': 'https://apigw-ivip.yarn-prod-ch1b.ch1b.ap.gbl:4435',
            'subCluster': 'BASIC-PROD-CH1B-5',
            'proxyUri': 'https://magnetar/cache',
        },
        {
            'Name': 'MTPrime-CO4-0',
            'RestServerUri': 'https://apigw-ivip.yarn-prod-co4.co4.ap.gbl:4431',
            'hdfsUri': 'hdfs://namenode0-ivip.mtprime-prod-co4.co4.ap.gbl',
            'webHdfsUri': 'http://namenode0-ivip.mtprime-prod-co4.co4.ap.gbl',
            'HttpFSUri': 'https://apigw-ivip.yarn-prod-co4.co4.ap.gbl:4436',
            'HttpFSAPIPath': '/webhdfs/v1/MTPrime-CO4-0',
            'resourceManagerUri': 'https://apigw-ivip.yarn-prod-co4.co4.ap.gbl:4435',
            'subCluster': 'MTPrime-PROD-CO4-0',
            'proxyUri': 'https://magnetar/cache',
        },
        {
            'Name': 'MTPrime-CO4-1',
            'RestServerUri': 'https://apigw-ivip.yarn-prod-co4.co4.ap.gbl:4431',
            'hdfsUri': 'hdfs://namenode1-ivip.mtprime-prod-co4.co4.ap.gbl',
            'webHdfsUri': 'http://namenode1-ivip.mtprime-prod-co4.co4.ap.gbl',
            'HttpFSUri': 'https://apigw-ivip.yarn-prod-co4.co4.ap.gbl:4436',
            'HttpFSAPIPath': '/webhdfs/v1/MTPrime-CO4-1',
            'resourceManagerUri': 'https://apigw-ivip.yarn-prod-co4.co4.ap.gbl:4435',
            'subCluster': 'MTPrime-PROD-CO4-1',
            'proxyUri': 'https://magnetar/cache',
        },
        {
            'Name': 'MTPrime-CO4-2',
            'RestServerUri': 'https://apigw-ivip.yarn-prod-co4.co4.ap.gbl:4431',
            'hdfsUri': 'hdfs://namenode0-ivip.mtprime-prod-co4.co4.ap.gbl',
            'webHdfsUri': 'http://namenode0-ivip.mtprime-prod-co4.co4.ap.gbl',
            'HttpFSUri': 'https://apigw-ivip.yarn-prod-co4.co4.ap.gbl:4436',
            'HttpFSAPIPath': '/webhdfs/v1/MTPrime-CO4-0',
            'resourceManagerUri': 'https://apigw-ivip.yarn-prod-co4.co4.ap.gbl:4435',
            'subCluster': 'MTPrime-PROD-CO4-2',
            'proxyUri': 'https://magnetar/cache',
        },
        {
            'Name': 'MTPrime-CO4-3',
            'RestServerUri': 'https://apigw-ivip.yarn-prod-co4.co4.ap.gbl:4431',
            'hdfsUri': 'hdfs://namenode3-ivip.mtprime-prod-co4.co4.ap.gbl',
            'webHdfsUri': 'http://namenode3-ivip.mtprime-prod-co4.co4.ap.gbl',
            'HttpFSUri': 'https://apigw-ivip.yarn-prod-co4.co4.ap.gbl:4436',
            'HttpFSAPIPath': '/webhdfs/v1/MTPrime-CO4-3',
            'resourceManagerUri': 'https://apigw-ivip.yarn-prod-co4.co4.ap.gbl:4435',
            'subCluster': 'MTPrime-PROD-CO4-3',
            'proxyUri': 'https://magnetar/cache',
        },
        {
            'Name': 'MTPrime-CO4-4',
            'RestServerUri': 'https://apigw-ivip.yarn-prod-co4.co4.ap.gbl:4431',
            'hdfsUri': 'hdfs://namenode4-ivip.mtprime-prod-co4.co4.ap.gbl',
            'webHdfsUri': 'http://namenode4-ivip.mtprime-prod-co4.co4.ap.gbl',
            'HttpFSUri': 'https://apigw-ivip.yarn-prod-co4.co4.ap.gbl:4436',
            'HttpFSAPIPath': '/webhdfs/v1/MTPrime-CO4-4',
            'resourceManagerUri': 'https://apigw-ivip.yarn-prod-co4.co4.ap.gbl:4435',
            'subCluster': 'MTPrime-PROD-CO4-4',
            'proxyUri': 'https://magnetar/cache',
        },
        {
            'Name': 'MTPrime-BN2-0',
            'RestServerUri': 'https://apigw-ivip.yarn-prod-bn2.bn2.ap.gbl:4431',
            'hdfsUri': 'hdfs://namenode0-ivip.mtprime-prod-bn2.bn2.ap.gbl',
            'webHdfsUri': 'http://namenode0-ivip.mtprime-prod-bn2.bn2.ap.gbl',
            'HttpFSUri': 'https://apigw-ivip.yarn-prod-bn2.bn2.ap.gbl:4436',
            'HttpFSAPIPath': '/webhdfs/v1/MTPrime-PROD-BN2-0',
            'resourceManagerUri': 'https://apigw-ivip.yarn-prod-bn2.bn2.ap.gbl:4435',
            'subCluster': 'MTPrime-PROD-BN2-0',
            'proxyUri': 'https://magnetar/cache',
        },
        {
            'Name': 'MTPrime-BN2-1',
            'RestServerUri': 'https://apigw-ivip.yarn-prod-bn2.bn2.ap.gbl:4431',
            'hdfsUri': 'hdfs://namenode1-ivip.mtprime-prod-bn2.bn2.ap.gbl',
            'webHdfsUri': 'http://namenode1-ivip.mtprime-prod-bn2.bn2.ap.gbl',
            'HttpFSUri': 'https://apigw-ivip.yarn-prod-bn2.bn2.ap.gbl:4436',
            'HttpFSAPIPath': '/webhdfs/v1/MTPrime-BN2-1',
            'resourceManagerUri': 'https://apigw-ivip.yarn-prod-bn2.bn2.ap.gbl:4435',
            'subCluster': 'MTPrime-PROD-BN2-1',
            'proxyUri': 'https://magnetar/cache',
        },
        {
            'Name': 'MTCmpl-CO4-0',
            'RestServerUri': 'https://apigw-ivip.yarn-prod-co4.co4.ap.gbl:4431',
            'hdfsUri': 'hdfs://namenode0-ivip.mtcmpl-prod-co4.co4.ap.gbl',
            'webHdfsUri': 'http://namenode0-ivip.mtcmpl-prod-co4.co4.ap.gbl',
            'HttpFSUri': 'https://apigw-ivip.yarn-prod-co4.co4.ap.gbl:4436',
            'HttpFSAPIPath': '/webhdfs/v1/MTCmpl-CO4-0',
            'resourceManagerUri': 'https://apigw-ivip.yarn-prod-co4.co4.ap.gbl:4435',
            'subCluster': 'MTCmpl-PROD-CO4-0',
            'proxyUri': 'https://magnetar/cache',
        },
    ],
};

module.exports = clustersConfig;
