name: Node CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  rest-server:
    name: CI for rest server on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [8, 10]
        os: [ubuntu-16.04, ubuntu-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}
    - name: Change directory to rest server
      run: cd src/rest-server
    - name: Install
      run: yarn install --frozen-lockfiles
    - name: Test
      run: yarn test

  webportal:
    name: CI for webportal on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [8, 10]
        os: [ubuntu-16.04, ubuntu-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}
    - name: Change directory to webportal
      run: cd src/webportal
    - name: Install
      run: yarn install --frozen-lockfiles
    - name: Build
      run: yarn build
    - name: Test
      run: yarn test
