# Copyright (c) Microsoft Corporation
# All rights reserved.
#
# MIT License
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
# documentation files (the "Software"), to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
# to permit persons to whom the Software is furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
# BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

FROM nvidia/cuda:8.0-cudnn5-devel-ubuntu16.04

ENV STAGE_DIR=/root/drivers \
    PYTHONPATH=/modules

RUN apt-get -y update && \
    apt-get -y install \
        build-essential \
        gcc \
        pciutils \
        bind9-host \
        bc \
        libssl-dev \
        software-properties-common \
        git \
        vim \
        wget \
        curl \
        make \
        jq \
        psmisc \
        python \
        python-dev \
        python-yaml \
        python-jinja2 \
        python-urllib3 \
        python-tz \
        python-nose \
        python-prettytable \
        python-netifaces \
        python-pip \
        git \
        realpath \
        module-init-tools && \
    pip install subprocess32 && \
    add-apt-repository -y ppa:ubuntu-toolchain-r/test && \
    apt-get -y update && \
    apt-get -y install g++-4.9 && \
    mkdir -p $STAGE_DIR

WORKDIR $STAGE_DIR

COPY install-* $STAGE_DIR/
RUN chmod u+x install-nvidia-drivers
RUN chmod u+x install-all-drivers

ENV NVIDIA_VERSION=384.81
ENV CUDA_VERSION=9.0.176

RUN wget --no-verbose https://developer.nvidia.com/compute/cuda/9.0/Prod/local_installers/cuda_${CUDA_VERSION}_${NVIDIA_VERSION}_linux-run && \
    chmod 750 ./cuda_${CUDA_VERSION}_${NVIDIA_VERSION}_linux-run && \
    ./cuda_${CUDA_VERSION}_${NVIDIA_VERSION}_linux-run --extract=$STAGE_DIR && \
    rm ./cuda_${CUDA_VERSION}_${NVIDIA_VERSION}_linux-run 
#    wget -q -O - /tmp https://github.com/NVIDIA/nvidia-docker/releases/download/v1.0.1/nvidia-docker_1.0.1_amd64.tar.xz | tar --strip-components=1 -C /usr/bin -Jxvf -
# cuda-linux64-rel-8.0.61-21551265.run  cuda-samples-linux-8.0.61-21551265.run  NVIDIA-Linux-x86_64-375.26.run
# http://us.download.nvidia.com/XFree86/Linux-x86_64/$NVIDIA_VERSION/NVIDIA-Linux-x86_64-$NVIDIA_VERSION.run
RUN ./NVIDIA-Linux-x86_64-${NVIDIA_VERSION}.run --extract-only && \
    rm ./NVIDIA-Linux-x86_64-${NVIDIA_VERSION}.run 

ENV NV_DRIVER=/var/drivers/nvidia/$NVIDIA_VERSION
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$NV_DRIVER/lib:$NV_DRIVER/lib64
ENV PATH=$PATH:$NV_DRIVER/bin

CMD ./install-all-drivers
